all:
	g++ -o main main.cpp -lGL -lGLU -lglut -lm
	g++ -o helixList helixList.cpp -lGL -lGLU -lglut -lm
	g++ -o ringList ringList.cpp -lGL -lGLU -lglut -lm
	g++ -o mouse mouse.cpp -lGL -lGLU -lglut -lm
	g++ -o mouseMotion mouseMotion.cpp -lGL -lGLU -lglut -lm
	g++ -o canvas canvas.cpp -lGL -lGLU -lglut -lm
	g++ -o menus menus.cpp -lGL -lGLU -lglut -lm